name: Package Application

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  package:
    strategy:
      matrix:
        include:
          - os: windows-latest
            java-version: '17'
          - os: ubuntu-latest
            java-version: '17'
          - os: macos-latest
            java-version: '17'
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot

      - name: Make gradlew executable
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew
        
      - name: Build with Gradle
        run: ./gradlew createInstaller --info
        
      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-installer
          path: |
            build/jpackage/*.msi
            build/jpackage/*.deb
            build/jpackage/*.dmg

  create-release:
    needs: package
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *-installer/*.msi
            *-installer/*.deb
            *-installer/*.dmg
